name: Mods verification
on: [push, pull_request]

jobs:
  manifest-checking:
    name: Manifest check
    uses: ./.github/workflows/manifest-check.yml
  verify-mods-versions:
    name: Verify all mods
    needs: [manifest-checking]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Run mod checks
        run: |
          python .github/verify_versions.py
