name: Check for tabs in JSON files

on: [push, pull_request]

jobs:
  check-for-tabs-in-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check JSON files for tabs
        run: |
          set -e

          for file in $(find . -type f -name '*.json'); do
            if grep --perl-regexp --quiet '\t' "$file"; then
              echo "Error: JSON file $file contains tabs."
              exit 1
            fi
          done
