name: Validate JSONs

on: [push, pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate package.json against local schema
        uses: cardinalby/schema-validator-action@v3
        with:
            file: 'verified-mods.json'
            schema: '.github/schema.json'
  verify-mods-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Run mod checks
        run: |
          python .github/verify_versions.py
