name: Validate JSONs

on: [push, pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Main
        run: |
          echo "FOO=$(ls -la)" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.FOO }}"
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./.github/schema.json
          INPUT_JSONS: ./verified-mods.json