name: Validate JSONs

on: [push, pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate package.json against local schema
        uses: cardinalby/schema-validator-action@v3
        with:
            file: 'verified-mods.json'
            schema: '.github/schema.json'
